### PR TITLE
Update to ember-cli 0.2.3

### LINKED ISSUE #33: latest beta deprecation warning
[deprecation](http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers)

[here](https://github.com/freshbooks/ember-responsive/blob/master/app/initializers/responsive.js#L30)

### PR DESCRIPTION
**Pull request by salzhrani**
Update to ember-cli 0.2.3
Fixes #33

### CODE REVIEW

**Comment by iStefo** [comment]
:+1: for this

**Comment by coladarci** [comment]
:+1: much needed!!

**Comment by alexBaizeau** [comment]
Thanks a bunch @salzhrani

**Comment by alexBaizeau** [comment]
I just published `1.1.0` on npm. Sorry for the delay

**Pull request merged**
