### PR TITLE
[RFC][NI] Fix breakpoints coherency across addon

### PR DESCRIPTION
**Pull request by telmaantunes**
Update breakpoints.js with the same breakpoints that are generated when installing this addon on a project, i.e. the ones from [here](https://github.com/freshbooks/ember-responsive/blob/master/blueprints/ember-responsive/files/__root__/breakpoints.js).

Considering that the app/breakpoint.js generated by this addon overrides the default one, this should cause no harm.

### CODE REVIEW

**Comment by k-fish** [comment]
Part of this PR is done by https://github.com/freshbooks/ember-responsive/pull/106, can you trigger another CI build (merge in master)?

**Comment by telmaantunes** [comment]
@k-fish yes, it was a colleague of mine, I will rebase :)

**Comment by telmaantunes** [comment]
@k-fish ready to go 👍

**Comment by k-fish** [comment]
@telmaantunes new version is out 2.0.5

**Comment by telmaantunes** [comment]
thanks! @k-fish

**Pull request merged**
