### PR TITLE
Add `breakpoints.js` to addon

### PR DESCRIPTION
**Pull request by elwayman02**
No reason not to include the default config in addon/, since it can easily be overridden in app/ for those who don't want to use the defaults.

Additionally, adds a VERY basic demo in the dummy app

Removes duplicate LICENSE file

### CODE REVIEW

**Comment by elwayman02** [comment]
Ideally we could also just update the existing [demo](https://github.com/f3ndot/ember-responsive-demo) and put it in the dummy app, so people have something they can play with when they clone this repo.

**Comment by jasonmit** [comment]
I would justimplement it in app not addon since extending really wouldnt be popular for breakpoints.js.  And in the case where they want to override you still would be bundling the unused addon breakpoints.js

**Comment by elwayman02** [comment]
:+1:

**Comment by elwayman02** [comment]
@jasonmit updated

**Comment by f3ndot** [comment]
I disagree with a default "set" of breakpoints only because the addon isn't intended to prescribe a particular responsive design (where we dictate what we think a "desktop view" etc. should be) but to afford the functionality for the user to decide for his or herself. To decide on a default is to change the goal of the addon, in my opinion.

That being said, I could be a crazy ol', pedantic coot and my colleagues @gigr and @alexBaizeau may care less and think it'd be convenient for our users to have a default set to draw from. However, another counterargument is that we choose :hankey: defaults and users override it anyway.

But! I completely agree with moving the demo app into the addon's dummy app. I've been thinking about doing that for a while but never got around to it.

**Comment by f3ndot** [comment]
To clarify: the set provided in the README.md was intended to be more of an example than a default.

**Comment by elwayman02** [comment]
That's fair enough...I don't actually necessarily agree with the example from the README, but I wanted to go with what had been provided previously. More than open to discussing changing it.

Personally, I think the addon *should* provide sensible defaults, as *most* users are just going to want something that works out of the box and supports the major layout sizes they deal with today. Now, maybe in the future the defaults will be "outdated" as different form factors emerge or change, but that's something we can update with a MAJOR version release following SemVer to let users of the addon know it's been updated accordingly.

Personally, I think most people are going to just copy the example from the README, slap it in their app, and go from there, because they don't want to think about setting media queries for their responsive app. The whole point of using this addon is to not have to think about it, because it "just works".

Additionally, every configuration step any tool adds between installation and usage is a step that can confuse or deter people who are not knowledgeable about the technology. In this case, the configuration is fairly simple, yes, but that's no reason not to provide defaults for those who may be new to Ember or even JavaScript and want to simply install this addon to take advantage of it without knowing what's going on under the hood. In my mind, the fact that these media queries are actually configurable is more of a feature for the 1%, not the masses who would rather just accept a default and move on.

**Comment by elwayman02** [comment]
FWIW, these are the breakpoints we use (as recommended by our designer) in our Ember app at work:

$screenWidthTablet:  1024px !default;
$screenWidthDesktop: 1200px !default;
$screenWidthLarge:   1600px !default;
$screenWidthXLarge:  1800px !default;

Here's another good [resource](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/) on standard device media queries

Perhaps the provided defaults could be something like this:

```
export default {
  mobile:  '(max-width: 768px)',
  tablet:  '(min-width: 769px) and (max-width: 1280px)',
  desktop: '(min-width: 1281px) and (max-width: 1600px)',
  large:   '(min-width: 1601px)'
};
```

**Comment by alexBaizeau** [comment]
Thanks!

**Comment by f3ndot** [comment]
We're gonna do some extra cleanup before releasing a new version with this change. Stay tuned!

**Comment by JKGisMe** [comment]
Just my 2 cents: I'm very much in favor of defaults. I want something easy to get started with and then I can make custom ones after. I'm waiting for this release to install the addon. Nice addition!

**Comment by amedrz** [comment]
These defaults seem ok to me. In case we'd need to overwrite, wouldn't be better to place that file within `config` folder?

**Comment by jasonmit** [comment]
> In case we'd need to overwrite, wouldn't be better to place that file within config folder?

You overwrite by implementing your own app/breakpoints.js.  App tree wins out over the addon tree when merging.

**Comment by amedrz** [comment]
@jasonmit yeah but what I'm suggesting is that, either way, the `config` folder would be a better place for `breakpoints.js` instead of the root directory. Wouldn't it be?

**Comment by jasonmit** [comment]
I haven't see good uses of the config folder that were meant for being evaluated on the client (other than environments).  But I could see why you would want to put them there.

**Comment by amedrz** [comment]
Thanks for giving it a thought. Just went through ember-cli website and didn't find any specific use for the config folder other than for the `environment.js` file. Still I feel like `breakpoints.js` doesn't belong to the root directory. What about putting these values within `ENV` or even `ENV.APP`?

**Comment by alexBaizeau** [comment]
The reason why we've put `breakpoint.js` in the root folder was because [liqui-fire](http://ef4.github.io/liquid-fire/#/transition-map) does that too with the transition map and it seemed like it had a similar purpose.

**Comment by johnunclesam** [comment]
Can we move breakpoints.js from app? `config` folder, environment.js, but not in root folder, please.

**Comment by k-fish** [comment]
@johnunclesam I agree that the root folder isn't an ideal location, but the file structure of ember apps is likely to change soon (https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md) so I'd prefer to wait instead of making two major breaking version changes in quick succession.

**Pull request merged**
