### PR TITLE
update ember-getowner-polyfill to remove deprecation

### PR DESCRIPTION
**Pull request by kellyselden**
Related https://github.com/rwjblue/ember-getowner-polyfill/pull/6

### CODE REVIEW

**Comment by kellyselden** [comment]
Could this get a release please?

**Comment by k-fish** [comment]
Sure

**Comment by kellyselden** [comment]
Thank you.

**Comment by Baukereg** [comment]
No release yet?

**Comment by k-fish** [comment]
👍

**Comment by houfeng0923** [comment]
not merged in  v2.0.1?

**Comment by k-fish** [comment]
@houfeng0923 if you look at the tag comparison, you can see it has merged (https://github.com/freshbooks/ember-responsive/compare/v2.0.0...v2.0.1).

Did you perhaps forget to clear your `node_modules` or am I missing something?

**Comment by houfeng0923** [comment]
@k-fish  ok . thanks for your information .

**Pull request merged**
