### PR TITLE
Make test support setBreakpoint IE11 compatible

### PR DESCRIPTION
**Pull request by raido**
Replace for..of loop with just for loop for IE11 compatibility.

Resolves: #302

### CODE REVIEW

**Comment by raido** [comment]
@alexBaizeau any chance of this getting merged and released?

**Comment by snewcomer** [comment]
@alexBaizeau If you have time!  This is a nice little addition for IE11 (hopefully this isn't applicable in a year 😆 )

**Comment by raido** [comment]
Any updates on the release? @alexBaizeau

**Comment by alexBaizeau** [comment]
I had a busy summer!

**Comment by alexBaizeau** [comment]
I published 4.0.1 Sorry for the delay and thanks for the PR!!

**Comment by raido** [comment]
Thank you!

**Pull request merged**
