### PR TITLE
BUGFIX: CP's are not firing on tracked media props

### LINKED ISSUE #338: CP's are not firing on version 4.0.0
Computed properties are not recomputed on media change.

Reproduction: https://github.com/freshbooks/ember-responsive/pull/339

### PR DESCRIPTION
**Pull request by rreckonerr**
Closes #338

### CODE REVIEW

**Comment by st-h** [comment]
commenting to confirm that this PR works fine with octane 👍

**Comment by antonbavykin1991** [comment]
works for me ;)

**Comment by knownasilya** [comment]
Any chance we can get this merged and released?

**Comment by rreckonerr** [comment]
I've asked folk in discord if they knew who to contact a while ago, and no luck :/

**Comment by calvin-fb** [comment]
@rreckonerr @st-h @antonbavykin1991 @knownasilya Sorry for the delay on this! Appreciate the fix. The folks who had been maintaining this repo are no longer around so it slipped under the radar. Looks like our travis builds are all jacked up so I'm going to try to fix that and merge as many other PRs as possible and target a release for early next week.

**Comment by calvin-fb** [comment]
Released as 4.0.2

**Pull request merged**
